# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WngLMng
email: wnglmng@qq.com
description: >
  嗨，我是王立明，一名来自黑龙江省鹤岗市的男生。现于无线生活（北京），从事互联网开发工作。
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wnglmng.com" # the base hostname & protocol for your site
paginate:	10 # The number of posts to show per page on your homepage

name: 'WngLMng'
bio: >
  嗨，我是王立明，一名来自黑龙江省鹤岗市的男生。现于无线生活（北京），从事互联网开发工作。
author_image: "/assets/images/author.jpg"
github_username:  WngLMng

permalink: /:year/:month/:title/
paginate_path: "pages/:num/"
highlighter: rouge

# Google Analytics
analytics_id: "86942437"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
