# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ahw9995
email: ahw9998@gmail.com
description: >
  개발과 관련된 기록들을 남기는 블로그
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ahw9995.github.io" # the base hostname & protocol for your site
paginate:	10 # The number of posts to show per page on your homepage

name: 'HyungWook Charles Ahn'
bio: >
  개발과 관련된 기록들을 남기는 블로그
author_image: "/assets/images/author.jpg"
github_username:  ahw9995

permalink: /:year/:month/:title/
paginate_path: "pages/:num/"
highlighter: rouge

# Google Analytics
# analytics_id: "86942437"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
